eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:     
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
  instance:
    preferIpAddress: true
logging:
  file: coomeva-pinosonline-fidelizacion.log
  path: ../logs
  
